services:
  - type: web
    name: newsletter-agent
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_AP_KEY
        sync: false
      - key: FLASK_ENV
        value: production
    healthCheckPath: /